version: "3"
services:
  br_db:
    image: postgres:alpine
    container_name: "br_db"
    env_file:
      - .env
      - config/private/${ENV:-dev}/secrets.env

  br_db_admin:
    image: dpage/pgadmin4
    env_file:
      - .env
      - config/private/${ENV:-dev}/secrets.env
    logging:
      driver: none
    container_name: "br_db_admin"
    depends_on:
      - br_db
    volumes:
      - ./config/pgadmin.json:/pgadmin4/servers.json

  br_web:
    image: nginx:latest
    container_name: "br_web"
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data:/app_data
    depends_on:
      - br_db_admin
      - br_react
      - br_django

  br_react:
    container_name: "br_react"
    image: node:alpine
    volumes:
      - ./frontend/:/home/node/app/
      - ./data:/app_data
      - ./config/private/${ENV:-dev}:/private/
      - ./config/scripts/startnode.sh:/startnode.sh:ro
    working_dir: /home/node/app/
    command: sh /startnode.sh
    env_file:
      - .env
      - config/private/${ENV:-dev}/secrets.env
      - config/private/${ENV:-dev}/super-secrets.env
    depends_on:
      - br_db
      - br_django

  br_django:
    container_name: "br_django"
    build: ./config/docker/django/${ENV:-dev}
    command: sh /startdjango.sh
    environment:
      - PIP_TARGET=/app/pip_modules
      - PYTHONPATH=/app/pip_modules
    volumes:
      - ./backend/:/app
      - ./data:/app_data
      - ./config/private/${ENV:-dev}:/private/
      - ./config/scripts/startdjango.sh:/startdjango.sh:ro
      - ./config/scripts/startdjango_user.sh:/startdjango_user.sh:ro
    env_file:
      - .env
      - config/private/${ENV:-dev}/secrets.env
      - config/private/${ENV:-dev}/super-secrets.env
      - config/private/${ENV:-dev}/stripe.env
    depends_on:
      - br_db

  br_stripe_dev_webhooks:
    container_name: "br_stripe_dev_webhooks"
    image: stripe/stripe-cli
    entrypoint: /start.sh
    command: listen --forward-to br_web:80/api/payments/webhook/
    volumes:
      - ./config/scripts/start-stripe-wh.sh:/start.sh:ro
      - ./config/private/dev/stripe_webhook:/mnt:rw
    env_file:
      - config/private/${ENV:-dev}/stripe.env
    depends_on:
      - br_web
