# Generated by Django 4.0.2 on 2022-05-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_eur_cent', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_eur_cent', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('checkout_session_id', models.CharField(max_length=128, unique=True)),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
